npm:
  image: node:9.3.0-alpine
  working_dir: /app
  entrypoint: npm
  command: start
  expose:
    - 3000
    - 3001
  ports:
    - "3000:3000"
    - "3001:3001"
  volumes:
    - ~/.npm:/root/.npm
    - ./:/app
  environment:
    VIRTUAL_HOST: www.pwds.test
    VIRTUAL_PORT: 3000