# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.3.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: HUGO_BASEURL=/test/design-system/`echo $CIRCLE_BRANCH | tr "/" "-"`/ npm run build

      - persist_to_workspace:
          root: ~/repo/dist
          paths:
            - ./*

  deploy:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "f7:98:44:45:14:93:a7:6a:58:f5:4d:0e:91:b6:db:a0"

      - attach_workspace:
          at: ~/repo/dist

      - deploy:
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build