# name: Cleanup branch on delete
# 
# on: [delete, workflow_dispatch]
# 
# jobs:
#   delete:
#     if: github.event.ref_type == 'branch'
#     name: 🗑 Delete branch
#     runs-on: ubuntu-latest
#     steps:
#       - name: 🛂 Extract branch name
#         shell: bash
#         run: |
#           HEAD_REF=$(printf "%q" "${{ github.head_ref }}")
#           HEAD_REF=${HEAD_REF/refs\/heads\//}
#           HEAD_REF=${HEAD_REF/\//-}
#           
#           echo "Sanitized branch name is $HEAD_REF"
# 
#           if [[ -z "$GITHUB_OUTPUT" ]]; then
#             echo "::set-output name=branch::$(eval printf "%s" "$HEAD_REF")"
#           else
#             echo "branch=$(eval printf "%s" "$HEAD_REF")" >> "$GITHUB_OUTPUT"
#           fi
#         id: extract_branch
# 
#       - name: 🧹 Clean deleted branch
#         uses: garygrossgarten/github-action-ssh@release
#         with:
#           command: rm -rf /srv/sites/www/www/design-system/${{ steps.extract_branch.outputs.branch }}
#           host: ${{ secrets.SERVER }}
#           username: ${{ secrets.USER }}
#           privateKey: ${{ secrets.SSH_KEY}}
#         uses: StephanThierry/ftp-delete-action@v2.1
